site_name: Tech Diff
site_url: https://tech-diff.com/
repo_url: https://github.com/pflooky/tech-diff
repo_name: tech-diff

plugins:
  - open-in-new-tab
  - optimize
  - social
  - privacy

theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select
    - toc.integrate
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_javascript:
  - path: https://code.jquery.com/jquery-3.7.0.js
    defer: true
  - path: https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js
    defer: true
  - path: https://cdn.datatables.net/fixedheader/3.4.0/js/dataTables.fixedHeader.min.js
    defer: true
  - path: https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js
    defer: true
  - path: https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js
    defer: true
  - path: https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js
    defer: true
  - path: https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js
    defer: true
  - path: https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js
    defer: true
  - javascripts/tableselect.js

extra_css:
  - https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css
  - https://cdn.datatables.net/fixedheader/3.4.0/css/fixedHeader.dataTables.min.css
  - https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pflooky/tech-diff
    - icon: fontawesome/brands/medium
      link: https://medium.com/@pflooky
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/peter-flook/
  analytics:
    provider: google
    property: G-351NDXP7ZF

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 'index.md'
  - File:
    - 'file/index.md'
    - Apache Avro:
      - Apache Hudi: 'file/apache_avro/apache_hudi.md'
      - Apache Iceberg: 'file/apache_avro/apache_iceberg.md'
      - Apache ORC: 'file/apache_avro/apache_orc.md'
      - Apache Parquet: 'file/apache_avro/apache_parquet.md'
      - CSV: 'file/apache_avro/csv.md'
      - Delta Lake: 'file/apache_avro/delta_lake.md'
    - Apache Hudi:
      - Apache Avro: 'file/apache_hudi/apache_avro.md'
      - Apache Iceberg: 'file/apache_hudi/apache_iceberg.md'
      - Apache ORC: 'file/apache_hudi/apache_orc.md'
      - Apache Parquet: 'file/apache_hudi/apache_parquet.md'
      - CSV: 'file/apache_hudi/csv.md'
      - Delta Lake: 'file/apache_hudi/delta_lake.md'
    - Apache Iceberg:
      - Apache Avro: 'file/apache_iceberg/apache_avro.md'
      - Apache Hudi: 'file/apache_iceberg/apache_hudi.md'
      - Apache ORC: 'file/apache_iceberg/apache_orc.md'
      - Apache Parquet: 'file/apache_iceberg/apache_parquet.md'
      - CSV: 'file/apache_iceberg/csv.md'
      - Delta Lake: 'file/apache_iceberg/delta_lake.md'
    - Apache ORC:
      - Apache Avro: 'file/apache_orc/apache_avro.md'
      - Apache Hudi: 'file/apache_orc/apache_hudi.md'
      - Apache Iceberg: 'file/apache_orc/apache_iceberg.md'
      - Apache Parquet: 'file/apache_orc/apache_parquet.md'
      - CSV: 'file/apache_orc/csv.md'
      - Delta Lake: 'file/apache_orc/delta_lake.md'
    - Apache Parquet:
      - Apache Avro: 'file/apache_parquet/apache_avro.md'
      - Apache Hudi: 'file/apache_parquet/apache_hudi.md'
      - Apache Iceberg: 'file/apache_parquet/apache_iceberg.md'
      - Apache ORC: 'file/apache_parquet/apache_orc.md'
      - CSV: 'file/apache_parquet/csv.md'
      - Delta Lake: 'file/apache_parquet/delta_lake.md'
    - CSV:
      - Apache Avro: 'file/csv/apache_avro.md'
      - Apache Hudi: 'file/csv/apache_hudi.md'
      - Apache Iceberg: 'file/csv/apache_iceberg.md'
      - Apache ORC: 'file/csv/apache_orc.md'
      - Apache Parquet: 'file/csv/apache_parquet.md'
      - Delta Lake: 'file/csv/delta_lake.md'
    - Delta Lake:
      - Apache Avro: 'file/delta_lake/apache_avro.md'
      - Apache Hudi: 'file/delta_lake/apache_hudi.md'
      - Apache Iceberg: 'file/delta_lake/apache_iceberg.md'
      - Apache ORC: 'file/delta_lake/apache_orc.md'
      - Apache Parquet: 'file/delta_lake/apache_parquet.md'
      - CSV: 'file/delta_lake/csv.md'
  - Job orchestration:
    - 'job_orchestration/index.md'
    - Apache Airflow:
      - Dagster: 'job_orchestration/apache_airflow/dagster.md'
      - Mage: 'job_orchestration/apache_airflow/mage.md'
      - Prefect: 'job_orchestration/apache_airflow/prefect.md'
    - Dagster:
      - Apache Airflow: 'job_orchestration/dagster/apache_airflow.md'
      - Mage: 'job_orchestration/dagster/mage.md'
      - Prefect: 'job_orchestration/dagster/prefect.md'
    - Mage:
      - Apache Airflow: 'job_orchestration/mage/apache_airflow.md'
      - Dagster: 'job_orchestration/mage/dagster.md'
      - Prefect: 'job_orchestration/mage/prefect.md'
    - Prefect:
      - Apache Airflow: 'job_orchestration/prefect/apache_airflow.md'
      - Dagster: 'job_orchestration/prefect/dagster.md'
      - Mage: 'job_orchestration/prefect/mage.md'
