site_name: Tech Diff
site_url: https://tech-diff.com/
repo_url: https://github.com/pflooky/tech-diff
repo_name: tech-diff

plugins:
  - open-in-new-tab
  - optimize
  - social

theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select
    - toc.integrate
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_javascript:
  - path: https://code.jquery.com/jquery-3.7.0.js
    defer: true
  - path: https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js
    defer: true
  - path: https://cdn.datatables.net/fixedheader/3.4.0/js/dataTables.fixedHeader.min.js
    defer: true
  - path: https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js
    defer: true
  - path: https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js
    defer: true
  - path: https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js
    defer: true
  - path: https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js
    defer: true
  - path: https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js
    defer: true
  - javascripts/tableselect.js

extra_css:
  - https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css
  - https://cdn.datatables.net/fixedheader/3.4.0/css/fixedHeader.dataTables.min.css
  - https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pflooky/tech-diff
    - icon: fontawesome/brands/medium
      link: https://medium.com/@pflooky
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/peter-flook/
  analytics:
    provider: google
    property: G-351NDXP7ZF

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 'index.md'
  - File: 'file/index.md'
  - Job_orchestration: 'job_orchestration/index.md'